### ISSUE TITLE
having trouble getting skills to load

### ISSUE THREAD

**Issue by splifcad** [Sablednah/LegendQuest#4]
I'm  having trouble getting any of the skills to load.  The skill.yml created in the plugin folder is empty as well as the /skill  folder created in the plugins folder.  I went so far as to try populating the skills.yml,  and then even creating a .yml entry in the /skill folder and still nothing.  

I have gotten passive skills to show up,  and the loadout option to scroll through skills works,  but am unsure where to start for the rest.

thanks for any help

**Comment by Sablednah** [comment]
The skills yaml - it just used to set defaults.   If you for example always use weaponmaster for +5 damage - you can set that default in there.

However your skills folder should not be empty.  It should have skills in it!  Did you download from dev.Bukkit or Spigot?  Or compile from the source here?

**Comment by splifcad** [comment]
easy fix, originally got it off bucket,  dl'd the spigot link and had the skill jar files.  Thanks, and awesome plugin.
